### ISSUE TITLE
State "Level.canvas" showing error "Failed to create the part's controls" on MacOS Sierra

### ISSUE THREAD

**Issue by plenge** [PhaserEditor2D/PhaserEditor#86]
When i create a new Phaser project, I am unable to view the level canvas file.
I get "Failed to create the part's controls" in the canvas window.

I am running v. 1.5.2 on MacOS Sierra (10.12.6)
I have pasted screenshot and error log.

Screenshot of editor:
<img width="1041" alt="screen shot 2018-09-19 at 12 09 32" src="https://user-images.githubusercontent.com/17022898/45747009-f02a5f80-bc04-11e8-844b-fb5db77a1e0c.png">

The error log contains the following.

```
!SESSION` 2018-09-19 12:02:41.672 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_112
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -cssTheme none -keyring /Users/jakobplenge/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -cssTheme none -keyring /Users/jakobplenge/.eclipse_keyring

!ENTRY org.eclipse.core.net 1 0 2018-09-19 12:02:45.153
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences

!ENTRY org.eclipse.e4.ui.workbench 4 0 2018-09-19 12:05:26.025
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at com.sun.javafx.font.MacFontFinder.populateFontFileNameMap(MacFontFinder.java:99)
	at com.sun.javafx.font.PrismFontFactory.getFullNameToFileMap(PrismFontFactory.java:1740)
	at com.sun.javafx.font.PrismFontFactory.getFontResource(PrismFontFactory.java:469)
	at com.sun.javafx.font.LogicalFont.getSlot0Resource(LogicalFont.java:194)
	at com.sun.javafx.font.LogicalFont.getDefaultAAMode(LogicalFont.java:409)
	at com.sun.javafx.font.LogicalFont.getStrike(LogicalFont.java:413)
	at com.sun.javafx.font.PrismFont.getStrike(PrismFont.java:73)
	at com.sun.javafx.text.PrismTextLayout.setContent(PrismTextLayout.java:138)
	at javafx.scene.text.Text.getTextLayout(Text.java:229)
	at javafx.scene.text.Text.needsFullTextLayout(Text.java:184)
	at javafx.scene.text.Text.access$200(Text.java:95)
	at javafx.scene.text.Text$2.invalidated(Text.java:389)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:109)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.scene.text.Text.setText(Text.java:370)
	at javafx.scene.text.Text.<init>(Text.java:129)
	at phasereditor.canvas.ui.editors.FrontGridPane.paintGridLabels(FrontGridPane.java:86)
	at phasereditor.canvas.ui.editors.FrontGridPane.repaint(FrontGridPane.java:56)
	at phasereditor.canvas.ui.editors.behaviors.UpdateBehavior.updateFromSettings(UpdateBehavior.java:244)
	at phasereditor.canvas.ui.editors.ObjectCanvas.init(ObjectCanvas.java:114)
	at phasereditor.canvas.ui.editors.CanvasEditor.initCanvas(CanvasEditor.java:463)
	at phasereditor.canvas.ui.editors.CanvasEditor.afterCreateWidgets(CanvasEditor.java:393)
	at phasereditor.canvas.ui.editors.CanvasEditor.createCanvasPartControl(CanvasEditor.java:381)
	at phasereditor.canvas.ui.editors.CanvasEditor.createDesignPage(CanvasEditor.java:311)
	at phasereditor.canvas.ui.editors.CanvasEditor.createPages(CanvasEditor.java:249)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:348)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:151)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:99)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:355)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:990)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:955)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:105)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:74)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:56)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:992)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:661)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:767)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:738)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:732)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:716)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1293)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.lambda$0(LazyStackRenderer.java:68)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4871)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:212)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:52)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:173)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:620)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:584)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:769)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:401)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1188)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3261)
	at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3176)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3158)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3153)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3117)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3098)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:600)
	at phasereditor.project.core.ProjectCore$3.run(ProjectCore.java:391)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4034)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3701)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at phasereditor.ide.intro.PhaserIDE2.start(PhaserIDE2.java:49)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

```

EDIT: Format

**Comment by PhaserEditor2D** [comment]
Are you using retina display?

**Comment by plenge** [comment]
I do not have the monospaced font, i will see if i can find get it somewhere to start with :) 
And yes, i am using a retina display, and a 4k monitor.

**Comment by plenge** [comment]
> Please, can you check if you have the "Monospaced" font in your system?

Are you sure that the font is named "Monospaced"? 
While I have, and can find many monospace fonts, I find no indication of one named "Monospaced".
Do you know where I will be able to find it?

**Comment by PhaserEditor2D** [comment]
The problem is that I have coded the "Monospaced" font, that it seems is not available in Retina systems.

Until we fix that, please try by installing any of these fonts:

https://www.fontsquirrel.com/fonts/list/classification/monospaced

You can install it following this guide:

https://support.apple.com/en-bh/HT201749

But first, just rename it to Monospaced.

**Comment by plenge** [comment]
Hi @PhaserEditor2D

Downloading and renaming a font does not seem to fix the problems.

I am not super busy getting going in this software, is there an estimate on when the fix approximately will be out? :)

// Plenge

**Comment by PhaserEditor2D** [comment]
No, I do not have an estimate. Let me try to do a quick patch for you today.

**Comment by PhaserEditor2D** [comment]
Please, download and uncompress this file:

[patch-1-issue-86.zip](https://github.com/PhaserEditor2D/PhaserEditor/files/2405411/patch-1-issue-86.zip)

It contains a single file `phasereditor.canvas.ui_1.5.2.20180907.jar`. You should replace the file of the same name in the folder `Phaser Editor/Phaser Editor.app/Contents/Eclipse/plugins`. MacOS shows the `Phaser Editor.app` as an application, so you should right-click on it and select `Show Package Content`.

Let me know if it works.

**Comment by plenge** [comment]
Hi @PhaserEditor2D 

Sorry for the late reply, I was caught up. It sadly did not work.

I have attached the errorlog.

[errorlog.log](https://github.com/PhaserEditor2D/PhaserEditor/files/2446153/errorlog.log)

**Comment by PhaserEditor2D** [comment]
Just give me a time to compile a new macos binary for you to test.

**Comment by PhaserEditor2D** [comment]
Hi @plenge 

Please can you try with this new release:

[http://phasereditor2d.com/files/v1.5.3/Phaser-Editor-1.5.3.GA.jre.macosx.zip](http://phasereditor2d.com/files/v1.5.3/Phaser-Editor-1.5.3.GA.jre.macosx.zip)

**Comment by plenge** [comment]
Hi @PhaserEditor2D 

I still have issues, i never got it to work on Sierra.
Now I recently upgraded til Mojave. But issues stil persist.

`java.lang.NullPointerException
	at com.sun.javafx.font.MacFontFinder.populateFontFileNameMap(MacFontFinder.java:99)
	at com.sun.javafx.font.PrismFontFactory.getFullNameToFileMap(PrismFontFactory.java:1740)
	at com.sun.javafx.font.PrismFontFactory.getFontResource(PrismFontFactory.java:469)
	at com.sun.javafx.font.LogicalFont.getSlot0Resource(LogicalFont.java:194)
	at com.sun.javafx.font.LogicalFont.getDefaultAAMode(LogicalFont.java:409)
	at com.sun.javafx.font.LogicalFont.getStrike(LogicalFont.java:413)
	at com.sun.javafx.font.PrismFont.getStrike(PrismFont.java:73)
	at com.sun.javafx.text.PrismTextLayout.setContent(PrismTextLayout.java:138)
	at javafx.scene.text.Text.getTextLayout(Text.java:229)
	at javafx.scene.text.Text.needsFullTextLayout(Text.java:184)
	at javafx.scene.text.Text.access$200(Text.java:95)
	at javafx.scene.text.Text$2.invalidated(Text.java:389)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:109)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.scene.text.Text.setText(Text.java:370)
	at javafx.scene.text.Text.<init>(Text.java:129)
	at phasereditor.canvas.ui.editors.FrontGridPane.paintGridLabels(FrontGridPane.java:85)
	at phasereditor.canvas.ui.editors.FrontGridPane.repaint(FrontGridPane.java:55)
	at phasereditor.canvas.ui.editors.behaviors.UpdateBehavior.updateFromSettings(UpdateBehavior.java:244)
	at phasereditor.canvas.ui.editors.ObjectCanvas.init(ObjectCanvas.java:114)
	at phasereditor.canvas.ui.editors.CanvasEditor.initCanvas(CanvasEditor.java:458)
	at phasereditor.canvas.ui.editors.CanvasEditor.afterCreateWidgets(CanvasEditor.java:389)
	at phasereditor.canvas.ui.editors.CanvasEditor.createCanvasPartControl(CanvasEditor.java:377)
	at phasereditor.canvas.ui.editors.CanvasEditor.createDesignPage(CanvasEditor.java:307)
	at phasereditor.canvas.ui.editors.CanvasEditor.createPages(CanvasEditor.java:245)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:348)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:151)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:99)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:355)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:990)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:955)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:105)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:74)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:56)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:992)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:661)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:767)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:738)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:732)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:716)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1293)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.lambda$0(LazyStackRenderer.java:68)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4871)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:212)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:52)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:173)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:620)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:584)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:769)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:401)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1188)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3261)
	at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3176)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3158)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3153)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3117)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3098)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:600)
	at phasereditor.assetexplorer.ui.views.AssetExplorer.showSelectionInEditor(AssetExplorer.java:137)
	at phasereditor.assetexplorer.ui.views.AssetExplorer$1.doubleClick(AssetExplorer.java:112)
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:831)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:828)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1459)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1258)
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:249)
	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:247)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:306)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4082)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3699)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at phasereditor.ide.intro.PhaserIDE2.start(PhaserIDE2.java:49)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)`

**Comment by plenge** [comment]
Hi @PhaserEditor2D 

I just figured it out, although i'm not sure excactly why.
Been trying to google several times, but finally came across something with the right issue.

Resetting my Mac's Font Book Library fixed the error.
https://github.com/asciidocfx/AsciidocFX/issues/290

**Comment by PhaserEditor2D** [comment]
This is the bug in JDK:

https://bugs.openjdk.java.net/browse/JDK-8089900

Note there is a workaround:

"The users have seen this issue when using both Mac OS X 10.10 and 10.9.5. 
Interestingly both users seemed to have Microsoft Office fonts installed. 

One user resolved the issue by "Restoring Standard Fonts" in the Font Book application."

Please try it. If it does not work we can try by using a different a newer Java version.

**Comment by plenge** [comment]
Thank you for using so much time. 
I guess i'll try to slowly install new fonts again and see where it fails :)

**Comment by PhaserEditor2D** [comment]
I am happy it is working now! Keep in touch!
